version: '3'
services:
  mysql:
    build: ./mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  postgres:
    build: ./postgres
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
